### ISSUE TITLE
language server crashing

### ISSUE THREAD

**Issue by Reissner** [twday/vscode-bibmanager#19]
The console of the bibtex language server shows 

```
home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:160
                let fieldInEntry = citation.hasOwnProperty(fieldQuery[1]);
                                            ^

TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at /home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:160:45
    at Generator.next (<anonymous>)
    at fulfilled (/home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:5:58)
[Info  - 10:09:29 PM] Connection to server got closed. Server will restart.
/home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:160
                let fieldInEntry = citation.hasOwnProperty(fieldQuery[1]);
                                            ^

TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at /home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:160:45
    at Generator.next (<anonymous>)
    at fulfilled (/home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:5:58)
[Info  - 10:09:30 PM] Connection to server got closed. Server will restart.
/home/ernst/.vscode/extensions/twday.bibmanager-2.0.0/server/out/server.js:160
                let fieldInEntry = citation.hasOwnProperty(fieldQuery[1]);
```

Seems a bug but maybe there is a workaround. 
I would like to understand what is going on.

**Comment by twday** [comment]
Hey @Reissner, I've not experienced this issue yet but the version of VS Code and the Language server package have both had major updates since the latest release on VS Code Marketplace.

I'm currently working on adding a tree view to the extension and will update the dependencies at the same time.

Hopefully that will fix the issue 🤞🏼
